import pandas as pd

#Remove columns with null values above 0.1 generated by rolling
def del_invalid_column(df:pd.DataFrame):
    column_drop_list=[]
    for column in df.columns:
        print(df[column].isnull().sum())
        print(df[column].isnull().sum()/df.shape[0])
        if df[column].isnull().sum()/df.shape[0]>=0.1:
            column_drop_list.append(column)
    df.drop(column_drop_list,axis=1,inplace=True)
    return df


#删除掉由于rolling导致nan的对应的天数,除了return以外
def del_nan_row(df:pd.DataFrame):
    df=df.unstack()
    df.dropna(axis=0,inplace=True)
    return df








